TuristickaAgencija/Controllers/GradoviController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TuristickaAgencija.EF;
using TuristickaAgencija.EntityModels;
using TuristickaAgencija.Helper;
using TuristickaAgencija.ViewModel;

namespace TuristickaAgencija.Controllers
{
    [Autorizacija(zaposlenik: true, putnikkorisnik: false)]

    public class GradoviController : Controller
    {
        private readonly MojContext _db;

        public GradoviController(MojContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            List<Gradovi> sviGradovi = _db.Gradovi.Include(x => x.Drzava).ToList();

            return View(sviGradovi);
            
        }
        [HttpGet]
        public IActionResult Dodavanje()
        {
            DrzavaListVM viewModel = new DrzavaListVM
            {
                Grad = new GradoviVM(),
                Drzave = _db.Drzava.ToList()
            };

            return View("Forma", viewModel);
        }


        [HttpPost]
        public IActionResult Snimi(DrzavaListVM model)
        {
            if (!ModelState.IsValid)
                return View("Forma", model);

            Gradovi grad;

            if (model.Grad.Id != 0)
            {
                grad = _db.Gradovi.Find(model.Grad.Id);
            }
            else
            {
                grad = new Gradovi();

                _db.Gradovi.Add(grad);
            }

            grad.NazivGrada = model.Grad.Naziv;

            grad.DrzavaId = model.Grad.DrzavaId;

            _db.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Izmjena(int id)
        {
            var grad = _db.Gradovi.Find(id);
            if (grad == null)
            {
                return RedirectToAction("Index");
            }

            DrzavaListVM viewModel = new DrzavaListVM
            {
                Grad = new GradoviVM(grad),
                Drzave = _db.Drzava.ToList()
            };

            return View("Forma", viewModel);
        }



        //public IActionResult Izbrisi(int id)
        //{
        //    var grad = _db.Gradovi.Find(id);
        //    if (grad == null)
        //    {
        //        return RedirectToAction("Index");
        //    }

        //    _db.Gradovi.Remove(grad);
        //    _db.SaveChanges();


        //    return RedirectToAction("Index");
        //}
        public IActionResult Izbrisi(int id)
        {
            Gradovi
                k = _db.Gradovi.Find(id);


           
            if (k == null)
            {
                /*tu brisem?*/
                Console.WriteLine("Nije moguce brisanje");

            }
            else
            {
                _db.Remove(k);

                _db.SaveChanges();


            }
            return RedirectToAction(nameof(Index));
        }
    }
}

TuristickaAgencija/Views/Gradovi/Forma.cshtml
@using TuristickaAgencija.ViewModel;
@model DrzavaListVM;

@{
    if (Model.Grad.Id == 0)
    {
        ViewData["Title"] = "Dodavanje grada";
    }
    else
    {
        ViewData["Title"] = "Izmjena grada";
    }
}

@if (!ViewData.ModelState.IsValid)
{
    <div class="alert alert-danger">
        @Html.ValidationSummary()
    </div>
}

@*<h3>@ViewData["Title"]</h3>
    <hr />*@
<form asp-controller="Gradovi" asp-action="Snimi">
    <input asp-for="Grad.Id" type="hidden" />

    <div class="form-group">
        <label asp-for="Grad.Naziv">Naziv</label>
        <input asp-for="Grad.Naziv" type="text" class="form-control">
    </div>



    <div class="form-group">
        <label asp-for="Grad.DrzavaId">Država</label>
        <select asp-for="Grad.DrzavaId" asp-items="@(new SelectList(Model.Drzave, "DrzavaId", "Naziv"))" class="form-control"></select>


    </div>
    <button type="submit" class="btn btn-primary">Spremi</button>
</form>

TuristickaAgencija/Views/Gradovi/Index.cshtml
@model List<TuristickaAgencija.EntityModels.Gradovi>

@{
    ViewData["Title"] = "Gradovi";
}
<table class="table table-hover">
    <thead>
        <tr>
            <th class="text-left">
                <a asp-controller="Home" asp-action="Index" class="btn btn-info btn-sm">Menu</a>
            </th>
        </tr>
    </thead>
</table>

@if (!Model.Any())
{
    <div class="alert alert-info clearfix">
        <span>Nema gradova za prikaz.</span>

        <a asp-controller="Gradovi" asp-action="Dodavanje" class="btn btn-info btn-xs float-right">Dodaj</a>
    </div>
}
else
{
    <table class="table table-hover">
        <thead>
            <tr>
                <th>
                    Naziv
                </th>

                <th>
                    Naziv države
                </th>
                <th class="text-right">
                    <a asp-controller="Gradovi" asp-action="Dodavanje" class="btn btn-info btn-sm">Dodaj</a>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var grad in Model)
            {
                <tr>
                    <td>@grad.NazivGrada</td>

                    <td>@grad.Drzava.Naziv</td>

                    <td class="text-right">
                        <a asp-controller="Gradovi" asp-action="Izmjena" asp-route-id="@grad.Id" class="btn btn-info btn-sm">Izmijeni</a>
                        <a asp-controller="Gradovi" asp-action="Izbrisi" asp-route-id="@grad.Id" class="btn btn-danger btn-sm">Izbriši</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}