TuristickaAgencija/Controllers/DrzaveController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TuristickaAgencija.EF;
using TuristickaAgencija.EntityModels;
using TuristickaAgencija.Helper;


namespace TuristickaAgencija.Controllers
{
    [Autorizacija(zaposlenik: true, putnikkorisnik: false)]
    public class DrzaveController : Controller
    {
        private readonly MojContext _db;
        public DrzaveController(MojContext db)
        {
            _db = db;
        }
        [HttpGet]
        public IActionResult Index()
        {
            var svePrikazi = _db.Drzava.ToList();
            return View(svePrikazi);
        }
        public IActionResult Dodaj()
        {
            return View("Forma", new Drzava());
        }
        [HttpGet]
        public IActionResult Izmjena(int id)
        {
            var drzava = _db.Drzava.Find(id);


            return View("Forma", drzava);
        }
        public IActionResult Snimi(Drzava model)
        {
            Drzava drzava;
            if (model.DrzavaId != 0)
            {
                drzava = _db.Drzava.Find(model.DrzavaId);
            }
            else
            {
                drzava = new Drzava();

                _db.Drzava.Add(drzava);
            }
            drzava.Naziv = model.Naziv;

            _db.SaveChanges();

            return RedirectToAction("Index");
        }
        //public IActionResult Izbrisi(int id)
        //{
        //    var drzava = _db.Drzava.Find(id);
        //    _db.Drzava.Remove(drzava);
        //    _db.SaveChanges();
        //    return RedirectToAction("Index");
        //}
        public IActionResult Izbrisi(int id)
        {
            Drzava
                k = _db.Drzava.Find(id);
            if (k == null)
            {


            }
            else
            {
                _db.Remove(k);

                _db.SaveChanges();


            }
            return RedirectToAction(nameof(Index));
        }
    }
}

TuristickaAgencija/Views/Drzave/Forma.cshtml
@using TuristickaAgencija.EntityModels;
@model Drzava;

@{
    if (Model.DrzavaId == 0)
    {
        ViewData["Title"] = "Dodavanje države";
    }
    else
    {
        ViewData["Title"] = "Izmjena države";
    }
}

@if (!ViewData.ModelState.IsValid)
{
    <div class="alert alert-danger">
        @Html.ValidationSummary()
    </div>
}

<h3>@ViewData["Title"]</h3>
<hr />
<form asp-controller="Drzave" asp-action="Snimi">
    <input asp-for="DrzavaId" type="hidden" />

    <div class="form-group">
        <label asp-for="Naziv">Naziv</label>
        <input asp-for="Naziv" type="text" class="form-control">
    </div>
    <button type="submit" class="btn btn-primary">Spremi</button>
</form>

TuristickaAgencija/Views/Drzave/Index.cshtml
@model List<TuristickaAgencija.EntityModels.Drzava>

@{
    ViewData["Title"] = "Države";
}
<table class="table table-hover">
    <thead>
        <tr>
            <th class="text-left">
                <a asp-controller="Home" asp-action="Index" class="btn btn-info btn-sm">Menu</a>
            </th>
        </tr>
    </thead>
</table>

@if (!Model.Any())
{
    <div class="alert alert-info clearfix">
        <span>Nema država za prikaz.</span>

        <a asp-controller="Drzave" asp-action="Dodaj" class="btn btn-info btn-xs float-right">Dodaj</a>
    </div>
}
else
{
    <table class="table table-hover">
        <thead>
            <tr>
                <th>
                    Naziv
                </th>
                <th class="text-right">
                    <a asp-controller="Drzave" asp-action="Dodaj" class="btn btn-info btn-sm">Dodaj</a>
                </th>

            </tr>
        </thead>
        <tbody>
            @foreach (var drzava in Model)
            {
                <tr>
                    <td>@drzava.Naziv</td>
                    <td class="text-right">
                        <a asp-controller="Drzave" asp-action="Izmjena" asp-route-id="@drzava.DrzavaId" class="btn btn-info btn-sm">Izmijeni</a>
                        <a asp-controller="Drzave" asp-action="Izbrisi" asp-route-id="@drzava.DrzavaId" class="btn btn-danger btn-sm">Izbriši</a>
                    </td>
                </tr>
            }
        </tbody>

    </table>
}