TuristickaAgencija/Controllers/VodicController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TuristickaAgencija.EF;
using TuristickaAgencija.EntityModels;
using TuristickaAgencija.Helper;
using TuristickaAgencija.ViewModel;

namespace TuristickaAgencija.Controllers
{
    public class VodicController : Controller
    {
        private readonly MojContext _db;
        public VodicController(MojContext db)
        {
            _db = db;
        }
        [Autorizacija(zaposlenik: true, putnikkorisnik: false)]

        public IActionResult SearchVodic(string searchString)
        {
            if (searchString == null)
            {
                List<VodicPrikaziVM> prikazi = _db.Vodic.Include(x => x.Putovanja)

                                            .Select(a => new VodicPrikaziVM()
                                            {
                                                Ime = a.Ime,
                                                Prezime = a.Prezime,
                                                Kontakt = a.Kontakt,
                                                JMBG = a.JMBG,
                                                Putovanje = a.Putovanja.NazivPutovanja,
                                                Slika=a.Slika
                                               

                                            }).ToList();
                return View("Index", prikazi);
            }
            List<VodicPrikaziVM> model = _db.Vodic.Include(x => x.Putovanja)
                                         .Where(x => x.Ime.ToLower().Contains(searchString.ToLower())
                                         || x.Prezime.ToLower().Contains(searchString.ToLower())
                                         || searchString == null)
                                             .Select(a => new VodicPrikaziVM()
                                             {
                                                 Ime = a.Ime,
                                                 Prezime = a.Prezime,
                                                 Kontakt = a.Kontakt,
                                                 JMBG = a.JMBG,
                                                 Putovanje = a.Putovanja.NazivPutovanja,
                                                 Slika = a.Slika


                                             }).ToList();

            return View("Index", model);
        }
        public IActionResult Index()
        {
            List<VodicPrikaziVM> model = _db.Vodic.Include(x => x.Putovanja).Select(
                k => new VodicPrikaziVM
                {
                    VodicId = k.VodicId,
                    Ime = k.Ime,
                    Prezime = k.Prezime,
                    JMBG = k.JMBG,
                    Kontakt = k.Kontakt,
                    Putovanje = k.Putovanja.NazivPutovanja,
                    Slika = k.Slika
                }).ToList();
            return View(model);
        }
        [Autorizacija(zaposlenik: true, putnikkorisnik: false)]

        public IActionResult Dodaj()
        {
            VodicUrediVM model = new VodicUrediVM();
            model.Putovanje = _db.Putovanja.Select(a => new SelectListItem
            {
                Value = a.PutovanjaId.ToString(),
                Text = a.NazivPutovanja
            }).ToList();
            return View(model);
        }
        [Autorizacija(zaposlenik: true, putnikkorisnik: false)]

        public IActionResult Snimi(VodicUrediVM input)
        {
            if (!ModelState.IsValid)
            {
                return View("Dodaj", input);

            }
            Vodic k;
            if (input.VodicID == 0)
            {
                k = new Vodic();
                _db.Add(k);

            }
            else
            {
                k = _db.Vodic.Find(input.VodicID);
            }

            if (input.Slika != null)
            {
                var memoryStream = new MemoryStream();


                input.Slika.CopyTo(memoryStream);
                var j = memoryStream.ToArray();
                k.Slika = j;

            }
            k.Ime = input.Ime;
            k.Prezime = input.Prezime;
            k.Kontakt = input.Kontakt;
            k.JMBG = input.JMBG;

            k.PutovanjaID = input.PutovanjeID;


            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        [Autorizacija(zaposlenik: true, putnikkorisnik: false)]

        public IActionResult Uredi(int VodicId)
        {

            Vodic v = _db.Vodic.Find(VodicId);
            if (v == null)
            {

                return RedirectToAction(nameof(Index));
            }

            VodicUrediVM model = new VodicUrediVM();
            model.Putovanje = _db.Putovanja.Select(o => new SelectListItem(o.NazivPutovanja, o.PutovanjaId.ToString())).ToList();
            model.PutovanjeID = v.PutovanjaID;
            model.Ime = v.Ime;
            model.Prezime = v.Prezime;
            model.Kontakt = v.Kontakt;
            model.JMBG = v.JMBG;





            return View(model);
        }
        [Autorizacija(zaposlenik: true, putnikkorisnik: false)]

        public IActionResult Obrisi(int VodicId)
        {
            Vodic v = _db.Vodic.Find(VodicId);
            if (v == null)
            {


            }
            else
            {
                _db.Remove(v);

                _db.SaveChanges();


            }
            return RedirectToAction(nameof(Index));
        }
    }
}

TuristickaAgencija/Views/Vodic/Dodaj.cshtml
@using TuristickaAgencija.Models;
@model TuristickaAgencija.ViewModel.VodicUrediVM;
@{
    ViewData["Title"] = "Dodaj";
}




<form enctype="multipart/form-data" asp-action="Snimi" method="post">
    @Html.HiddenFor(s => s.VodicID)
    <div class="form-group">
        <label>Ime </label>
        <input asp-for="Ime" class="form-control" />
        <span asp-validation-for="Ime" class="text-danger"></span>
        <br />
    </div>
    <div class="form-group">
        <label>Ime </label>
        <input asp-for="Prezime" class="form-control" />
        <span asp-validation-for="Prezime" class="text-danger"></span>
        <br />
    </div>
    <div class="form-group">
        <label>Kontakt </label>
        <input asp-for="Kontakt" class="form-control" />
        <span asp-validation-for="Kontakt" class="text-danger"></span>
        <br />
    </div>
    <div class="form-group">
        <label>JMBG </label>
        <input asp-for="JMBG" class="form-control" />
        <span asp-validation-for="JMBG" class="text-danger"></span>
        <br />
    </div>




    <div class="form-group">
        <label>Putovanja</label>
        <select asp-for="PutovanjeID" asp-items="@Model.Putovanje" class="form-control"></select>
        <span asp-validation-for="PutovanjeID" class="text-danger"></span>

    </div>

    <div class="form-group">
        <label>Slika </label>
        <input asp-for="Slika" type="file" accept="image/*" class="form-control" />

        <br />
    </div>





    <input type="submit" value="Snimi" class="btn btn-warning" />
</form>

TuristickaAgencija/Views/Vodic/Index.cshtml
@model List<TuristickaAgencija.ViewModel.VodicPrikaziVM>
@using TuristickaAgencija.Helpers

@{
    ViewData["Title"] = "Vodici";
}
<br />

<br />

@using (Html.BeginForm("Index", "Vodic", FormMethod.Get))
{



    <div class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
        <input type="text" name="searchString" class="form-control bg-light border-0 small" placeholder="Unesite ime ili prezime..." aria-label="Search" aria-describedby="basic-addon2">
        <button class="btn btn-info" type="submit" asp-action="SearchVodic">
            <i class="fa fa-search fa-sm "></i>
            Pretrazi
        </button>

    </div>
}
<table class="table table-hover">
    <thead>
        <tr>
            <th class="text-left">
                <a asp-controller="Home" asp-action="Index" class="btn btn-info btn-sm">Menu</a>
            </th>
        </tr>
    </thead>
</table>

@if (!Model.Any())
{
    <div class="alert alert-info clearfix">
        <span>Nema vodica za prikaz.</span>

        <a asp-controller="Vodic" asp-action="Dodaj" class="btn btn-info btn-xs float-right">Dodaj</a>
    </div>
}

else
{
    <table class="table table-hover">
        <thead>
            <tr>
                <th>
                    Ime
                </th>
                <th>
                    Prezime
                </th>
                <th>
                    Kontakt
                </th>
                <th>
                    JMBG
                </th>
                <th>
                    Putovanje
                </th>
                <th>
                    Photo
                </th>

                <th class="text-right">
                    <a asp-controller="Vodic" asp-action="Dodaj" class="btn btn-info btn-sm">Dodaj</a>
                </th>
            </tr>
        </thead>

        <tbody>
            @foreach (var i in Model)
            {

                <tr>

                    <td>@i.Ime</td>
                    <td>@i.Prezime</td>
                    <td>@i.Kontakt</td>
                    <td>@i.JMBG</td>


                    <td>@i.Putovanje</td>

                    <td><img alt="Nema slike" src="@SlikaBase64.Prikaz(i.Slika)" height="200" width="150" /></td>
                    <td class="text-right">

                        <a asp-action="Uredi" asp-route-VodicId="@i.VodicId" class="btn btn-info btn-sm">Uredi</a>


                    </td>
                    <td class="text-right">
                        @*<td><a href="/Vodici/Obrisi?VodicId=@i.VodicId" class="btn btn-danger btn-sm">Obrisi</a></td>*@
                        <a asp-action="Obrisi" asp-route-VodicId="@i.VodicId" class="btn btn-danger btn-sm">Obrisi</a>
                    </td>

                </tr>
            }
        </tbody>
    </table>
}
<style>
    .alert a {
    color: #fff;
    text-decoration: none;
   
    font-size: 15px;
    width: 10%;
    padding: 5px;
}
</style>

TuristickaAgencija/Views/Vodic/Uredi.cshtml
@using TuristickaAgencija.Models;
@model TuristickaAgencija.ViewModel.VodicUrediVM;
@{
    ViewData["Title"] = "Uredi";
}



<form asp-action="Snimi">
    @Html.HiddenFor(s => s.VodicID)
    <div class="form-group">
        <label>Ime </label>
        <input asp-for="Ime" class="form-control" />
        <span asp-validation-for="Ime" class="text-danger"></span>
        <br />
    </div>
    <div class="form-group">
        <label>Ime </label>
        <input asp-for="Prezime" class="form-control" />
        <span asp-validation-for="Prezime" class="text-danger"></span>
        <br />
    </div>
    <div class="form-group">
        <label>Kontakt </label>
        <input asp-for="Kontakt" class="form-control" />
        <span asp-validation-for="Kontakt" class="text-danger"></span>
        <br />
    </div>
    <div class="form-group">
        <label>JMBG </label>
        <input asp-for="JMBG" class="form-control" />
        <span asp-validation-for="JMBG" class="text-danger"></span>
        <br />
    </div>




    <div class="form-group">
        <label>Putovanja</label>
        <select asp-for="PutovanjeID" asp-items="@Model.Putovanje" class="form-control"></select>
        <span asp-validation-for="PutovanjeID" class="text-danger"></span>

    </div>

    <div class="form-group">
        <label>Slika </label>
        <input asp-for="Slika" type="file" accept="image/*" class="form-control" />

        <br />
    </div>





    <input type="submit" value="Snimi" class="btn btn-warning" />
</form>