TuristickaAgencija/Controllers/PrevozController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TuristickaAgencija.EF;
using TuristickaAgencija.EntityModels;
using TuristickaAgencija.Helper;
using TuristickaAgencija.ViewModel;

namespace TuristickaAgencija.Controllers
{
    public class PrevozController : Controller
    {
        private readonly MojContext _db;

        public PrevozController(MojContext db)
        {
            _db = db;
        }
        [Autorizacija(zaposlenik: true, putnikkorisnik: true)]

        public IActionResult Index()
        {
            List<PrevozPrikaziVM> prevozPrikazi = _db.Prevoz.Select(x => new PrevozPrikaziVM
            {
                Id=x.Id,
                Firma = x.Firma.Naziv,
                BrojMjesta=x.BrojMjesta,
                CijenaPoMjestu=x.CijenaPoMjestu,
                TipPrevoza=x.TipPrevoza
            }).ToList();
            return View("Index",prevozPrikazi);
        }
        [Autorizacija(zaposlenik: true, putnikkorisnik: false)]

        public IActionResult Dodaj()
        {
            PrevozDodajUrediVM model = new PrevozDodajUrediVM();
            model.Firma = _db.Firma.Select (x=>new SelectListItem
            {
                Value=x.Id.ToString(),
                Text=x.Naziv
            }).ToList();
            return View("Dodaj",model);
        }
        [Autorizacija(zaposlenik: true, putnikkorisnik: false)]

        public IActionResult Snimi(PrevozDodajUrediVM model)
        {
            Prevoz prevoz;
            if (model.Id != 0)
            {
                prevoz = _db.Prevoz.Find(model.Id);

            }
            else
            {
                prevoz = new Prevoz();
                _db.Prevoz.Add(prevoz);
            }


            prevoz.FirmaID = model.FirmaID;
            prevoz.TipPrevoza = model.TipPrevoza;
            prevoz.BrojMjesta = model.BrojMjesta;
            prevoz.CijenaPoMjestu = model.CijenaPoMjestu;

            _db.SaveChanges();

            return RedirectToAction("Index");
        }
        [Autorizacija(zaposlenik: true, putnikkorisnik: false)]

        public IActionResult Obrisi(int id)
        {
            var prevoz = _db.Prevoz.Find(id);
            _db.Prevoz.Remove(prevoz);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        [Autorizacija(zaposlenik: true, putnikkorisnik: false)]

        public IActionResult Uredi(int id)
        {
            var prevoz = _db.Prevoz.Find(id);

            if (prevoz == null)
            {

                return RedirectToAction(nameof(Index));
            }
            PrevozDodajUrediVM model = new PrevozDodajUrediVM
            {
                Id=prevoz.Id,
                FirmaID=prevoz.FirmaID,
                TipPrevoza=prevoz.TipPrevoza,
                BrojMjesta=prevoz.BrojMjesta,
                CijenaPoMjestu=prevoz.CijenaPoMjestu
            };
            model.Firma = _db.Firma.Select(x => new SelectListItem
            {
                Value = x.Id.ToString(),
                Text = x.Naziv
            }).ToList();

            return View("Dodaj",model );
        }
    }
    }

TuristickaAgencija/Views/Prevoz/Dodaj.cshtml
@using TuristickaAgencija.Models;
@model TuristickaAgencija.ViewModel.PrevozDodajUrediVM;
@{
    ViewData["Title"] = "Dodaj";
}




    <form enctype="multipart/form-data" asp-action="Snimi" method="post">
        @Html.HiddenFor(s => s.Id)

        <div class="form-group">
            <label>Firma</label>
            <select asp-for="FirmaID" asp-items="@Model.Firma" class="form-control"></select>
            @Html.ValidationMessageFor(model => model.Firma, "", new { @class = "text-danger" })


        </div>
        <div class="form-group">
            <label>Tip prevoza </label>
            <input asp-for="TipPrevoza" class="form-control" />
            @Html.ValidationMessageFor(model => model.TipPrevoza, "", new { @class = "text-danger" })

            <br />
        </div>
        <div class="form-group">
            <label>Broj mjesta </label>
            <input asp-for="BrojMjesta" class="form-control" />
            @Html.ValidationMessageFor(model => model.BrojMjesta, "", new { @class = "text-danger" })

            <br />
        </div>
        <div class="form-group">
            <label>Cijena </label>
            <input asp-for="CijenaPoMjestu" class="form-control" />
            @Html.ValidationMessageFor(model => model.CijenaPoMjestu, "", new { @class = "text-danger" })

            <br />
        </div>
       





        <input type="submit" value="Snimi" class="btn btn-warning" />
    </form>

TuristickaAgencija/Views/Prevoz/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model List<TuristickaAgencija.ViewModel.PrevozPrikaziVM>


@{

}

<table class="table table-hover">
    <thead>
        <tr>
            <th class="text-left">
                <a asp-controller="Home" asp-action="Index" class="btn btn-info btn-sm">Menu</a>
            </th>
        </tr>
    </thead>
</table>
@if (!Model.Any())
{
    <div class="alert alert-info clearfix">
        <span>Nema prevoza za prikaz.</span>

        <a asp-controller="Prevoz" asp-action="Dodaj" class="btn btn-info btn-xs float-right">Dodaj</a>
    </div>
}
else
{
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Firma</th>
                <th>Tip prevoza</th>
                <th>Broj mjesta</th>
                <th>Cijena po mjesta</th>
                <th class="text-right">
                    <a asp-controller="Prevoz" asp-action="Dodaj" class="btn btn-info btn-sm">Dodaj</a>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var x in Model)
            {
            <tr>
                <td>@x.Firma</td>
                <td>@x.TipPrevoza</td>
                <td>@x.BrojMjesta</td>
                <td>@x.CijenaPoMjestu</td>
                <td class="text-right">
                    <a asp-controller="Prevoz" asp-action="Uredi" asp-route-id="@x.Id" class="btn btn-info btn-sm">Uredi</a>
                    <a asp-controller="Prevoz" asp-action="Obrisi" asp-route-id="@x.Id" class="btn btn-danger btn-sm">Obriši</a>
                </td>
            </tr>
            }

        </tbody>

    </table>


}